---

- hosts: localhost
  gather_facts: false
  # become: yes
  # become_method: sudo

  vars_files:
    - group_vars/common.yml
    - group_vars/aws.vpc.yml
  
  roles:
    - roles/aws_create_vpc
#    - roles/docker
  
  tasks:
    - name: Testing get_vpc_facts
      include_tasks: roles/aws_create_vpc/tasks/get_vpc_facts.yml
