---

- name: Demo to provision AWS VPC and EC2
  hosts: localhost
  gather_facts: false
  # become: yes
  # become_method: sudo

  vars_files:
    - group_vars/common.yml
    - group_vars/aws.vpc.yml
  
  roles:
    - roles/aws_create_vpc
    - roles/aws_provision_ec2
#    - roles/docker

- name: Install Docker CE into EC2 instances
  hosts: ec2_nodes
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False

  vars_files:
    - group_vars/common.yml
  
  roles:
    - { role: roles/docker, become: yes }
