---

- name: Demo to provision AWS VPC and EC2
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/common.yml
    - group_vars/aws.vpc.yml
  
  roles:
    - roles/aws_create_vpc
    - roles/aws_provision_ec2
#    - roles/docker

- name: Install Docker CE into EC2 instances
  hosts: ec2_nodes
  # user: centos  
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  # gather_facts: true

  vars_files:
    - group_vars/common.yml
  
  roles:
    - { role: roles/docker, become: yes, become_method: sudo }
    # - roles/docker
