---
# tasks file for roles/docker

# This Role requires a RHEL / CENTOS base OS

# This role performs the following:
# - Install and Configure Docker CE
# - Pull/Run nginx container

- name: START Role docker
  debug:
    msg: "START execution of role/docker"

- name: Update all current installed packages
  yum:
    name: "*"
    state: "latest"
    update_cache: "yes"
    use_backend: yum

- name: Add the gpg key for the Docker repo
  rpm_key:
    key: "{{ docker.gpg_key }}"
    state: "present"

- name: Add Docker repo from the remote url
  get_url:
    url: "{{ docker.repo_url }}"
    dest: "{{ docker.repo_path }}"
    mode: 0644

- name: Install Docker-CE and dependency packages
  yum:
    name: "{{ item }}"
    state: "installed"
    update_cache: "yes"
    use_backend: yum
  with_items: "{{ docker.packages }}"

- name: Install pip
  easy_install:
    name: pip
    state: latest

# This is required so we can use the Ansible docker_image and docker_container modules
- name: Install the Docker SDK for Python
  pip:
    name: "{{ item }}"
    extra_args: "-I"
  with_items: "{{ docker.pip }}"

- name: Start Docker and configure as a boot startup service
  service:
    name: "docker"
    state: "restarted"
    enabled: "yes"

- name: Create docker network
  docker_network:
    name: "{{ docker.network_name }}"

- name: Create Nginx container and connect to network
  docker_container:
    name: "{{ ansible_hostname }}-nginx"
    image: "{{ nginx.image }}"    
    # pull: yes
    hostname: "{{ ansible_hostname }}-nginx"
    networks:
      - name: "{{ docker.network_name }}"
    exposed_ports: "{{ nginx.exposed_ports }}"
    published_ports: "{{ nginx.published_ports }}"