---
# defaults file for roles/docker

docker:
  sudo_user: "centos"
  gpg_key: "https://download.docker.com/linux/centos/gpg"
  repo_url: "https://download.docker.com/linux/centos/docker-ce.repo"
  repo_path: "/etc/yum.repos.d/docker-ce.repo"
  packages:
    - "yum-utils"
    - "device-mapper-persistent-data"
    - "lvm2"
    - "docker-ce"
  pip:
    - "docker"
  network_name: "mydocker-net"

nginx:
  image: "nginx:1.15"
  exposed_ports:
    - 80
    - 8080
    - 443
  published_ports:
    - 80:80
    - 8080:8080
    - 443:443