---
# host_vars/aws.vpc.yml

# VPC CIDR block
vpc_cidr: 10.250.0.0/16

vpc_subnets:
  public-az1:
    cidr: 10.250.0.0/22
    az: "{{ aws_region }}a"
  # public-az2:
  #   cidr: 10.250.4.0/22
  #   az: "{{ aws_region }}b"
  # private-az1:
  #   cidr: 10.250.32.0/21
  #   az: "{{ aws_region }}a"
  # private-az2:
  #   cidr: 10.250.40.0/21
  #   az: "{{ aws_region }}b"

vpc_security_groups:
  # - name: allow-all
  #   descripton: Allow internal VPC traffic
  #   rules:
  #     - proto: all
  #       group_name: allow-all
  #       ports: all
  - name: allow-all-ssh
    description: Allow remote public SSH
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: allow-all-http
    description: Allow public http/https traffic
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 8080
          - 443