---
# Gather and Set facts variables about the VPC:
# - VPC ID
# - VPC Subnet IDs
# - VPC Security Group IDs
# - VPC IGW ID

# GET VPC by name
- name: GET facts - VPC
  ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ aws_vpc_name }}"
  register: my_vpc_facts

# SET VPC ID
- name: SET fact VPC ID
  set_fact:
    my_vpc_id: "{{ my_vpc_facts.vpcs[0].id }}"

- name: DEBUG my_vpc_id
  debug:
    var: my_vpc_id
  when: DEBUGMODE

# --------

# GET VPC Subnet IDs
- name: GET facts - VPC subnet IDs
  ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ my_vpc_id }}"
  register: my_vpc_subnet_facts

# SET VPC Subnet IDs
- name: SET fact - VPC Subnet IDs
  set_fact:
    my_vpc_subnet_ids: "{{ vpc_subnet_ids | default({}) | combine({ (item.tags.Name | default('default')): item.id }) }}"
  loop: "{{ my_vpc_subnet_facts.subnets }}"

- name: DEBUG my_vpc_subnet_ids
  debug:
    var: my_vpc_subnet_ids
  when: DEBUGMODE

# --------

# GET VPC Security Group IDs
- name: GET facts - VPC Security Group IDs
  ec2_group_facts:
    filters:
      vpc-id: "{{ my_vpc_id }}"
  register: my_vpc_sg_facts

# SET VPC Security Group IDs
- name: SET facts - VPC Security Group IDs
  set_fact:
    my_vpc_sg_ids: "{{ my_vpc_sg_ids | default({}) | combine({ (item.group_name | default('default')): item.group_id }) }}"
  loop: "{{ my_vpc_sg_facts.security_groups }}"

- name: DEBUG my_vpc_sg_ids
  debug:
    var: my_vpc_sg_ids
  when: DEBUGMODE

# --------

# GET VPC IGW ID
- name: GET facts - VPC IGW ID
  ec2_vpc_igw_facts:
    filters:
      attachment.vpc-id: "{{ my_vpc_id }}"
  register: my_vpc_igw_facts

# SET VPC IGW ID
- name: SET facts - VPC IGW ID
  set_fact:
    my_vpc_igw_id: "{{ my_vpc_igw_facts.internet_gateways[0].internet_gateway_id }}"

- name: DEBUG my_vpc_igw_id
  debug:
    var: my_vpc_igw_id
  when: DEBUGMODE